version: '3'

services:
  web:
    build: .
    command: bash -c "python3 distDrawBoard/manage.py makemigrations && python3 distDrawBoard/manage.py migrate && python3 distDrawBoard/manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000